#import oscillator_strength
from . import oscillator_strengths
from .oscillator_strengths import oscillator_strength
#from .oscillator_strengths import oscillator_strength_s
from .oscillator_strengths import oscillator_strength_convergence
